version: '3'

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    ports:
      - "7000:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    ports:
      - "7001:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    ports:
      - "7002:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge